language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: DEPENDENCIES='dev'
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
  - composer update $COMPOSER_FLAGS

script:
   - ./vendor/bin/phpunit tests

before_deploy:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - export PATH=.:$PATH
  - rm -Rf ./vendor
  - composer install --no-dev -o
  - box.phar build

deploy:
  provider: releases
  file: comp_phpapi.phar
  skip_cleanup: true
  on:
    tags: true
    php: 7.0
    condition: COMPOSER_FLAGS != "--prefer-lowest"
